## Ejercicios: Estructura de Datos - Arrays 

### Nivel 1: Introducción a Arrays con el módulo array
1. Creación y acceso:

    - Crea un array de tipo 'i' (entero) con los números del 1 al 5.
    - Imprime el array completo.
    - Accede e imprime el tercer elemento del array.
    - Accede e imprime el último elemento del array utilizando un índice negativo.

In [ ]:
import array

# Crear un array de enteros
a = array.array('i', [1, 2, 3, 4, 5])
print(a)  # Salida: array('i', [1, 2, 3, 4, 5])

# Acceder e imprimir el tercer elemento
print(a[2])  # Salida: 3

# Acceder e imprimir el último elemento (índice negativo)
print(a[-1])  # Salida: 5

2. Operaciones básicas:

    - Crea un array de tipo 'f' (flotante) con los números 2.5, 3.7, 1.1 y 4.9.
    - Agrega el número 5.2 al final del array.
    - Inserta el número 3.0 en la segunda posición del array.
    - Elimina el primer elemento del array.
    - Imprime el array modificado.

In [ ]:
import array

# Crear un array de flotantes
a = array.array('f', [2.5, 3.7, 1.1, 4.9])

# Agregar al final
a.append(5.2)

# Insertar en la segunda posición (índice 1)
a.insert(1, 3.0)

# Eliminar el primer elemento
a.pop(0)  # También se puede usar a.remove(2.5)

print(a)  # Salida: array('f', [3.0, 3.7, 1.1, 4.9, 5.2])

### Nivel 2: Arrays Multidimensionales con NumPy
3. Creación y acceso:

    - Crea un array bidimensional (matriz) de 3x3 con los números del 1 al 9.
    - Imprime la matriz completa.
    - Accede e imprime el elemento que está en la segunda fila y tercera columna.
    - Accede e imprime la primera fila completa.

In [ ]:
import numpy as np

# Crear una matriz 3x3
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matriz)
# [[1 2 3]
#  [4 5 6]
#  [7 8 9]]

# Acceder a un elemento específico (fila 1, columna 2)
print(matriz[1, 2])  # Salida: 6

# Acceder a la primera fila completa
print(matriz[0, :])  # Salida: [1 2 3]

4. Operaciones con NumPy:

    - Crea un array unidimensional con los números del 10 al 20.
    - Calcula la suma de todos los elementos del array.
    - Calcula el promedio de los elementos del array.
    - Encuentra el valor máximo y el valor mínimo del array.

In [ ]:
import numpy as np

# Crear un array unidimensional
array_uni = np.array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

# Suma de elementos
suma = np.sum(array_uni)
print(f"Suma: {suma}")  # Salida: Suma: 165

# Promedio de elementos
promedio = np.mean(array_uni)
print(f"Promedio: {promedio}")  # Salida: Promedio: 15.0

# Valor máximo y mínimo
maximo = np.max(array_uni)
minimo = np.min(array_uni)
print(f"Máximo: {maximo}, Mínimo: {minimo}")  # Salida: Máximo: 20, Mínimo: 10

### Nivel 3: Desafío con Arrays
5. Búsqueda y filtrado:

    - Crea un array con números aleatorios (puedes usar np.random.randint()).
    - Escribe una función que reciba el array y un número como argumento.
    - La función debe retornar una nueva lista con todos los elementos del array que sean mayores que el número dado.
    - Adicionalmente, la función debe imprimir la posición (índice) de cada elemento encontrado.

In [ ]:
import numpy as np

def buscar_y_filtrar(array, numero):
    mayores = []
    for i, elemento in enumerate(array):
        if elemento > numero:
            mayores.append(elemento)
            print(f"Elemento {elemento} encontrado en la posición {i}")
    return mayores

# Ejemplo de uso
mi_array = np.random.randint(0, 100, 20)  # Array de 20 números entre 0 y 99
numero_busqueda = 50
resultado = buscar_y_filtrar(mi_array, numero_busqueda)
print(f"Elementos mayores que {numero_busqueda}: {resultado}")

#### ¡No te rindas!
Recuerda que la clave para dominar los arrays está en la práctica constante. Intenta resolver los ejercicios por tu cuenta y, si te encuentras con alguna dificultad, no dudes en consultar la documentación de Python o buscar ejemplos en línea. ¡Mucho éxito en tu aprendizaje!